import os
from reportlab.pdfgen import canvas
from openpyxl import Workbook


# Function to create a sample PDF
def create_pdf(output_file):
    from reportlab.lib.pagesizes import letter
    print(f"Creating PDF: {output_file}")
    
    c = canvas.Canvas(output_file, pagesize=letter)
    width, height = letter
    
    # Add title and content
    c.setFont("Helvetica-Bold", 16)
    c.drawString(100, height - 100, "Sample PDF Document")
    
    c.setFont("Helvetica", 12)
    text = """
    This is a sample document generated by the automated writer.
    You can add dynamic content here based on your data or logic.
    
    Example: Adding content programmatically to this PDF document.
    """
    
    # Draw multi-line text
    text_object = c.beginText(100, height - 150)
    for line in text.split("\n"):
        text_object.textLine(line)
    c.drawText(text_object)
    
    # Save the PDF
    c.save()
    print(f"PDF Created Successfully: {output_file}")


# Function to create a sample Excel file
def create_excel(output_file):
    print(f"Creating Excel file: {output_file}")
    
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Sample Data"
    
    # Add Header Row
    headers = ["ID", "Name", "Role", "Department"]
    sheet.append(headers)

    # Add sample data
    data = [
        [1, "Alice", "Manager", "HR"],
        [2, "Bob", "Developer", "Engineering"],
        [3, "Charlie", "Analyst", "Finance"],
        [4, "David", "Administrator", "IT"]
    ]
    
    for row in data:
        sheet.append(row)

    # Save the Excel file
    workbook.save(output_file)
    print(f"Excel file created successfully: {output_file}")


# Main execution point
def main():
    # Define output paths
    pdf_output = os.path.join(os.getcwd(), "sample_document.pdf")
    excel_output = os.path.join(os.getcwd(), "sample_data.xlsx")

    # Generate the documents
    create_pdf(pdf_output)
    create_excel(excel_output)


if __name__ == "__main__":
    main()
